version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=reactnativeapp
      - POSTGRES_DB=reactnativeapp_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: