version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=reactnativeapp
      - POSTGRES_DB=reactnativeapp_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
  api:
      build: ./api
      ports:
        - '3000:3000'
      env_file:
      - .env
      depends_on:
        - db
      volumes:
        - ./api:/usr/src/app
        - /usr/src/app/node_modules
        
volumes:
  postgres_data: